### ISSUE TITLE
warning after compile

### ISSUE THREAD

**Issue by boxxxie** [psfblair/exdn#1]
warning: the dependency :calendar requires Elixir "~> 1.2.0 or ~> 1.1.0 or ~> 1.0.0" but you are running on v1.3.3

**Comment by psfblair** [comment]
I'll update the calendar version soon. Thanks!

**Comment by naomijub** [comment]
This PR updates calendar https://github.com/psfblair/exdn/pull/3

**Comment by psfblair** [comment]
Thanks for that. Sorry I dropped the ball on this one.

**Comment by naomijub** [comment]
Fixing CI https://github.com/psfblair/exdn/pull/4

**Comment by psfblair** [comment]
Thank you!
