### ISSUE TITLE
`from_elixir/1` mangles emoji

### ISSUE THREAD

**Issue by samm81** [psfblair/exdn#6]
hi there :) this is probably not an issue with `exdn` itself, but with the underlying `erldn` ? I am not sure.

```elixir
iex(80)> %{a: "🟢"} |> Exdn.from_elixir!() |> IO.puts()
{:a "ð¢"}
:ok
```

**Comment by samm81** [comment]
yeah looks to be `erldn`

```elixir
iex(84)> :erldn.to_string("🟢")
[~c"\"", [240, 159, 159, 162], ~c"\""]
```

**Comment by samm81** [comment]
no, actually, those 4 bytes are correct

```elixir
iex(98)> :erldn.to_string("🟢")
[~c"\"", [240, 159, 159, 162], ~c"\""]
iex(99)> <<240, 159, 159, 162>>
"🟢"
iex(100)> Exdn.from_elixir("🟢")
{:ok, <<34, 195, 176, 194, 159, 194, 159, 194, 162, 34>>}
iex(101)> <<34>>
"\""
```

so `erldn` is giving `<<240, 159, 159, 162>>` but `exdn` is giving `<<195, 176, 194, 159, 194, 159, 194, 162>>`

**Comment by samm81** [comment]
the problem appears to be here: https://github.com/psfblair/exdn/blob/60f0a40ff66f3fe898e2c86c9ac3a468742401a8/lib/exdn.ex#L316

```elixir
  def from_elixir!(elixir_data) do
    erldn_intermediate = to_erldn_intermediate(elixir_data)
    :erldn.to_string(erldn_intermediate) |> to_string
  end
```

the `[~c"\"", [240, 159, 159, 162], ~c"\""]` is getting passed to `to_string/1`, and that seems to be mangling it

**Comment by samm81** [comment]
ok so `:erlang.list_to_binary` properly converts it back to an emoji 🎉 !

```elixir
iex(27)> :erldn.to_string("🟢") |> :erlang.list_to_binary
"\"🟢\""
```

it also works for more complex structures:
```elixir
iex(34)> :erldn.to_string({:map, [a: "🟢"]}) |> :erlang.list_to_binary
"{:a \"🟢\"}"
```

**Comment by psfblair** [comment]
Before I approve your PR, I want to understand better why this is happening. (Please note that I haven't been coding in Elixir for many years, and haven't been actively maintaining this repo, so my knowledge is rusty.)

My understanding is that strings in Elixir are Strings are UTF-8 encoded binaries, so it's not entirely clear to me why `to_string/1` isn't behaving as expected. I am seeing some explanation in this post <[https://groups.google.com/g/elixir-lang-core/c/h9TspwoiNys](https://groups.google.com/g/elixir-lang-core/c/h9TspwoiNys)> and also note that `String.from_char_list/1` was replaced by `String.from_char_data/1`, which was later replaced by `List.to_string/1 `<[(https://github.com/elixir-lang/elixir/issues/2067#issuecomment-250918185)](https://github.com/elixir-lang/elixir/issues/2067#issuecomment-250918185)>. 

I am thinking that `List.to_string/1` is probably the function to use here. Thoughts?

**Comment by samm81** [comment]
so I added a test

```elixir
  test "string with unicode emoji converts to EDN" do
    assert Exdn.from_elixir!("hello 😊") == "\"hello 😊\""
  end
```

which fails (as expected)

```
$ mix test
  1) test string with unicode emoji converts to EDN (ExdnTest)
     test/exdn_test.exs:456
     Assertion with == failed
     code:  assert Exdn.from_elixir!("hello 😊") == "\"hello 😊\""
     left:  "\"hello ð\x9F\x98\x8A\""
     right: "\"hello 😊\""
     stacktrace:
       test/exdn_test.exs:457: (test)

```
then I updated `from_elixir!/1` to `:erldn.to_string(erldn_intermediate) |> List.to_string()`

but it still fails with the same error as above

then I updated to `:erldn.to_string(erldn_intermediate) |> :erlang.list_to_binary()`

and the test passes

I took a look at the `List.to_string/1` docs:

> Note that this function expects a list of integers representing Unicode code
points. If you have a list of bytes, you must instead use the :binary module
(:binary).

turns out `:binary` has a `list_to_bin/1` so I gave that a shot, updating `from_elixir/1` to be `:erldn.to_string(erldn_intermediate) |> :binary.list_to_bin()`

and the test passed :tada: 

checking to [docs for `:binary.list_to_bin/1`](https://www.erlang.org/doc/man/binary#list_to_bin-1) it says

> Works exactly as [erlang:list_to_binary/1](https://www.erlang.org/doc/man/erlang#list_to_binary-1), added for completeness.

so either work 🤷

---

as for _why_ `:binary.list_to_bin/1` is needed instead of `to_string/1` I think our clue is in the `List.to_string/1` docs quoted above: "this function expects a list of integers representing Unicode code points. If you have a list of bytes, you must instead use the :binary module". `:erldn.to_string/1` seems to be returning a list of bytes rather than a list of integers representing unicode code points. indeed we can check to see what the codepoints would be...

```elixir
iex> String.to_charlist("🟢")
[128994]
```

also just to double check I took a look at `erldn` and I'm pretty sure the logic for conversion is happening [here](https://github.com/marianoguerra/erldn/blob/aecf2a48fa92ba81c9c1efbee3cd596b1714fb40/src/erldn.erl#L37)

```erlang
to_string(Value, Accum) when is_binary(Value) ->
    ["\"", escape_string(binary_to_list(Value)), "\""|Accum];
```

so `erldn` is using erlang's `binary_to_list` and looking at [the erlang docs](https://www.erlang.org/doc/man/erlang#binary_to_list-1) it says...

> Returns a list of integers corresponding to the bytes of Binary.

so a list of bytes! meaning we have to use `:binary.bin_to_list/1`

**Comment by samm81** [comment]
I've added the test to the PR, & changed `:erlang.list_to_binary/1` to :binary.list_to_bin/1`, as the `List.to_string/1` docs explicitly mention the `:binary` module

**Comment by psfblair** [comment]
Thanks very much for your patience and your help with this. I merged your PR, and created a release version 2.2.1 to include your change. (It also bumps the Elixir version to 1.12 because I was having trouble with GitHub CI and noticed that 1.11 is now off security support. https://endoflife.date/elixir)

**Comment by samm81** [comment]
:raised_hands: thanks very much for your package!

it seems that `2.2.1` hasn't quite made it onto `hex` yet - does it take a couple days?

**Comment by psfblair** [comment]
Apologies, it was so long since I published this package that I had transferred to a new machine and had a whole rigmarole getting the correct credentials. It's up now.
